name: Integration Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '**.py'
      - './requirements.txt'
  push:
    branches:
      - austinkline/localtests-merged
jobs:
  gremlin-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install
        run: |
          pip install -e .
      - name: Install gremlin-server
        run: |
          ./scripts/setup-gremlin-server.sh
      - name: Run Gremlin Tests
        env:
          JAVA_OPTIONS: "-Xms512m -Xmx4096m -Xss2m"
          GRAPH_NOTEBOOK_CONFIG: /tmp/graph_notebook_config_integration_test.json
        run: |
          /tmp/apache-tinkerpop-gremlin-server-3.5.2/bin/gremlin-server.sh start
          cat /tmp/graph_notebook_config_integration_test.json
          echo "waiting for 10 seconds while gremlin-server starts..."
          sleep 10
          pytest -m "gremlin and not iam and not neptune"
      - name: Cleanup
        run: |
          pkill -f gremlin-server
  sparql-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Set up Java (for Blazegraph)
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install
        run: |
          pip install -e .
      - name: Install blazegraph
        run: |
          ./scripts/setup-blazegraph.sh
      - name: Run SPARQL Tests
        env:
          GRAPH_NOTEBOOK_CONFIG: /tmp/graph_notebook_config_integration_test.json
        run: |
          /tmp/blazegraph-tgz-2.1.6-SNAPSHOT/bin/blazegraph.sh start
          echo "waiting for 10 seconds while server starts"
          sleep 10
          pytest -m "sparql and not iam and not neptune"
      - name: Cleanup
        run: |
          pkill -f blazegraph